### ISSUE TITLE
[*] Plaese Connect To Internet!! or address site not found

### ISSUE THREAD

**Issue by AmirHosseinBaderan** [ali2004-linux/ddos#1]
Hello ali 
I am amir hossin i found a **_**Problem**_** in your program 
When I Connected to net work that say "[*] Plaese Connect To Internet!! or address site not found"
or When I try for test Https webs That say "[*] Plaese Connect To Internet!! or address site not found"
please Solve the problem

**Comment by alihemmatnia** [comment]
یا ادرس سایتت اشتباهه یا اینترنت وصل نی اینا رو چک کن من واس خودم کار میکنه

**Comment by alihemmatnia** [comment]
https
رو نزن اولش فقط ادرس سایت رو بزن مثلا google.com

**Comment by alihemmatnia** [comment]
> Hello ali
> I am amir hossin i found a **_**Problem**_** in your program
> When I Connected to net work that say "[_] Plaese Connect To Internet!! or address site not found" or When I try for test Https webs That say "[_] Plaese Connect To Internet!! or address site not found"
> please Solve the problem

امیر سوکت با 
https 
فک کنم سازگار نیس برا همین

**Comment by AmirHosseinBaderan** [comment]
برای من که کار نکرد Sent from my Huawei phone-------- Original message --------From: Ali <notifications@github.com>Date: Thu, Jun 11, 2020, 6:54 AMTo: ali2004-linux/ddos <ddos@noreply.github.com>Cc: amir hossin <amir0hossin0pr@gmail.com>, Author <author@noreply.github.com>Subject: Re: [ali2004-linux/ddos] [*] Plaese Connect To Internet!! or address site not found (#1)

یا ادرس سایتت اشتباهه یا اینترنت وصل نی اینا رو چک کن من واس خودم کار میکنه

**Comment by A1python** [comment]
@Amir-Hossin-pr  bro,
don't type http:// or https:// just type domain name, Ex: python3 ddos.py 
google.com

**Comment by alihemmatnia** [comment]
fixed

**Comment by A1python** [comment]
hey bro can you add "hacktoberfest" in lable on all pull request which i done before.
please bro do that i done very hardwork on your script, thanks.

**Comment by A1python** [comment]
> fixed

hey bro can you add "hacktoberfest" in lable on all pull request which i done before.
please bro do that i done very hardwork on your script, thanks.
